# Default configuration file for running IsoSlam
log_level: "warning"
output_dir: output
bam_file: data/bam/.bam
gtf_file: data/gtf/
bed_file: data/bed/
vcf_file: data/vcf/
forward_reads:
  from: "T"
  to: "C"
reverse_reads:
  from: "A"
  to: "G"
summary_counts:
  file_pattern: "**/*.tsv"
  separator: "\t"
  groupby:
    - Transcript_id
    - Chr
    - Strand
    - Start
    - End
    - Assignment
    - Conversions
    - filename
  output:
    outfile: summary_counts.tsv
    sep: "\t"
    index: false
plot: false
