name: Bug report
description: Create a report to help us improve
title: "[bug]: "
labels: ["bug"]
projects: ["sudlab/1"]
assignees:
  - ""
body:
  - type: markdown
    attributes:
      value: |
        For installation and configuration instructions please refer to the repositories
        [README](https://github.com/sudlab/IsoSLAM)

        **NB** Please copy and paste commands and output rather than including screenshots as sharing text facilitates recreating and investigating the error.

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      description: A Checklist is provided below for you to track each of the subsequent tasks.
      options:
        - label: Describe the bug.
          required: true
        - label: Include the configuration file.
          required: true
        - label: To Reproduce
          required: true
        - label: Copy of the output.
          required: true
        - label: The exact command that failed. This is what you typed at the command line, including any options.
          required: true
        - label: IsoSLAM version, this is reported by `isoslam --version`
          required: true
        - label: Operating System and Python Version
          required: true
  - type: textarea
    id: describe-the-bug
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is and what may be causing it.
    validations:
      required: true
  - type: textarea
    id: copy-of-output
    attributes:
      label: Copy of the output
      description: |
        Please copy and paste the output from your terminal below. At a minimum this should include the bottom section showing where the error arose and the subsequent output.
    validations:
      required: true
  - type: textarea
    id: config-file
    attributes:
      label: Include the configuration file
      description: |
        Please include the configuration file you have used. If no configuration file was specified with the `-c`/`--config-file` option the defaults were used, please use the `isoslam create-config --filename crash.yaml` to save these to the `crash.yaml` file and copy the contents below.
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: To Reproduce
      description: |
        If it is possible to share the files (e.g. via cloud services) that caused the error that would greatly assist in reproducing and investigating the problem. In addition the _exact_ command used that failed should be pasted below.
    validations:
      required: false
  - type: dropdown
    id: version-isoslam
    attributes:
      label: IsoSLAM Version
      description: What version of our software are you running? You can find this out using `pip show isoslam`.
      options:
        - "0.0.1"
        - "Git main branch"
      default: 1
    validations:
      required: true
  - type: dropdown
    id: version-python
    attributes:
      label: Python Version
      description: |
        What version of Python are you running? If unsure type `python --version`.
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
      default: 3
    validations:
      required: true
  - type: dropdown
    id: version-os
    attributes:
      label: Operating System
      description: |
        What Operating System are you running?
      options:
        - Windows
        - MacOS Intel (pre-2021)
        - MacOS M1/M2 (post-2021)
        - GNU/Linux
      default: 3
    validations:
      required: true
  - type: textarea
    id: version-dependencies
    attributes:
      label: Python Packages
      description: |
        If you are able to provide a list of your installed packages that may be useful. The best way to get this is to copy and paste the results of typing `pip freeze`.
    validations:
      required: false
