name: Tests (pytest)

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    paths:
      - "**.csv"
      - "**.npy"
      - "**.out"
      - "**.pkl"
      - "**.png"
      - "**.py"
      - "**.toml"
      - "**.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"] # "windows-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip and install test dependencies
        run: |
          pip install --upgrade virtualenv
          pip install --upgrade pip setuptools
          virtualenv --upgrade-embed-wheels
          # Install build dependencies for now (see
          # https://github.com/cgat-developers/cgat-apps/issues/134#issuecomment-2503431974)
          pip install numpy
          pip install Cython
          pip install pysam
          pip install wheel
          pip install --no-build-isolation cgatcore
          pip install --no-build-isolation git+https://github.com/cgat-developers/cgat-apps@v0.7.4
          pip install --no-build-isolation -e .[tests]
      - name: Test with pytest
        run: |
          pytest --cov=isoslam --cov-report=xml --mpl -x
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5

      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5
